opt_in_rules:
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_string
  - empty_xctest_method
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - quick_discouraged_call
  - single_test_class
  - redundant_nil_coalescing
  - sorted_first_last
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - redundant_type_annotation

disabled_rules:
  - superfluous_disable_command

excluded:
  - Pods
  - CodeGenerated
  - DerivedData

identifier_name:
  excluded:
    - id

custom_rules:
  focused_quick_tests:
    included: ".*\\Spec.swift"
    name: "Focuded Quick Test"
    regex: 'f(it\(|describe\(|context\()'
    message: "Remove focused test before commit"

line_length: 150
